# Generated by Django 5.2.4 on 2025-07-20 22:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item del menú',
                'verbose_name_plural': 'Items del menú',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EatInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('menu', models.TextField()),
                ('mesa', models.PositiveIntegerField(blank=True, null=True)),
                ('zona', models.CharField(choices=[('north', 'Norte'), ('south', 'Sur'), ('east', 'Este'), ('west', 'Oeste'), ('center', 'Centro')], default='center', max_length=10)),
                ('numero_personas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado_pago', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('servicio_mesa', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatin_orders_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Mesero')),
            ],
            options={
                'verbose_name': 'Pedido en mesa',
                'verbose_name_plural': 'Pedidos en mesa',
            },
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('menu', models.TextField()),
                ('mesa', models.PositiveIntegerField(blank=True, null=True)),
                ('zona', models.CharField(choices=[('north', 'Norte'), ('south', 'Sur'), ('east', 'Este'), ('west', 'Oeste'), ('center', 'Centro')], default='center', max_length=10)),
                ('numero_personas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado_pago', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('direccion_envio', models.TextField()),
                ('costo_envio', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('tiempo_estimado_entrega', models.PositiveIntegerField(default=30)),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Mesero')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido con envío',
                'verbose_name_plural': 'Pedidos con envío',
            },
        ),
        migrations.CreateModel(
            name='TakeAwayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('menu', models.TextField()),
                ('mesa', models.PositiveIntegerField(blank=True, null=True)),
                ('zona', models.CharField(choices=[('north', 'Norte'), ('south', 'Sur'), ('east', 'Este'), ('west', 'Oeste'), ('center', 'Centro')], default='center', max_length=10)),
                ('numero_personas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado_pago', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('empaque', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('tiempo_preparacion', models.PositiveIntegerField(default=15)),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeaway_orders_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Mesero')),
            ],
            options={
                'verbose_name': 'Pedido para llevar',
                'verbose_name_plural': 'Pedidos para llevar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eatin_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.eatinorder')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem')),
                ('shipping_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.shippingorder')),
                ('takeaway_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.takeawayorder')),
            ],
            options={
                'verbose_name': 'Item de la orden',
                'verbose_name_plural': 'Items de la orden',
            },
        ),
    ]
