# Generated by Django 5.2.4 on 2025-07-21 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='eatin_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eatin_items', to='orders.eatinorder'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_items', to='orders.shippingorder'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='takeaway_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takeaway_items', to='orders.takeawayorder'),
        ),
    ]
