# Generated by Django 5.2.4 on 2025-07-21 03:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_plato', models.CharField(help_text='Nombre del plato', max_length=150, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del plato', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('disponibilidad', models.BooleanField(default=True, help_text='Indica si el plato está disponible')),
            ],
            options={
                'verbose_name': 'Plato del Menú',
                'verbose_name_plural': 'Platos del Menú',
                'ordering': ['nombre_del_plato'],
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del camarero', max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Género del camarero', max_length=1)),
                ('experiencia', models.PositiveIntegerField(default=0, help_text='Años de experiencia')),
                ('sueldo', models.DecimalField(decimal_places=2, help_text='Sueldo mensual del camarero', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('zona', models.CharField(help_text='Zona del restaurante asignada', max_length=50)),
            ],
            options={
                'verbose_name': 'Camarero',
                'verbose_name_plural': 'Camareros',
                'ordering': ['nombre'],
            },
        ),
    ]
